// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"shortlink/database"
	"shortlink/handler"
	"shortlink/repository"
	"shortlink/service"
)

// Injectors from wire.go:

func InitializeWire() (*handler.Handler, error) {
	db := database.NewDatabase()
	userRepositoryInterface := repository.NewUserRepository(db)
	authServiceInterface := service.NewAuthService(userRepositoryInterface)
	authHandlerInterface := handler.NewAuthHandler(authServiceInterface)
	handlerHandler := handler.NewHandler(authHandlerInterface)
	return handlerHandler, nil
}
